### ISSUE TITLE
Make mclwrap use its own package names and not Math's

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/mclwrap#21]
Mclwrap's bilinear group classes are currently found under `org.cryptimeleon.math.structures.groups.elliptic.type3.mcl`.

I would like to make Mclwrap not fake being part of Math like that anymore, for example using a directory structure such as `org.cryptimeleon.mclwrap.bn254`. 

I just added standalone representation tests to mclwrap (didn't have those before) and they seem to collect all of Math's classes as well, due to passing `org.cryptimeleon.math` to `StandaloneReprTest`. Obviously Mclwrap is not going to include standalone repr tests for all those classes. That problem can be solved by giving Mclwrap its own packaging structure.

What do you think @JanBobolz ?

**Comment by JanBobolz** [comment]
Hard agree. The Java package names should be consistent with the gradle project names, i.e. org.cryptimeleon.mclwrap.stuff

Good catch!

**Comment by rheitjoh** [comment]
Fixed as part of #20
